Logical: LogCzAdmissionEvaluation
Id: LogAdmissionEvaluationCz
Title: "A.2.4 - Stav při přijetí (cz)"
Description: """Nemocniční propouštěcí zpráva - Stav při přijetí - A.2.4 CZ poznámka: Nepovinná sekce uvádět pouze v případě významu pro zajištění kontinuity péče. """
* objektivniNalez 0..1 BackboneElement "A.2.4.1 - Objektivní nález " """Objektivní nález"""
  * datum 0..1 dateTime "A.2.4.1.1 - Datum a čas" """Datum a čas vyšetření pacienta lékařem v průběhu jeho přijímání k hospitalizaci"""
  * provedl 0..1 BackboneElement "A.2.4.1.2 - Provedl" """Identifikuje osobu, která  vyšetření provedla nebo je zdrojem informací o výsledku vyšetření. Tato osoba nemusí být totožná s autorem dokumentu."""
  * anthropometrickeUdaje 0..* BackboneElement "A.2.4.1.3 - Anthropometrické údaje" """Výsledky antropometrických měření pacienta: Požadované: výška, hmotnost, BMI (automatický výpočet z uvedených hodnot) Volitelné: obvod hlavy, hrudníku, břicha…"""
    * text 0..1 BackboneElement "A.2.4.1.3.1 - Výsledky měření textem" """Textový popis výsledku vyšetření"""
    * vysledek 0..1 BackboneElement "A.2.4.1.3.2 - Parametrický záznam vyšetření" """Parametrický zápis výsledku vyšetření."""
      * popisVysetreni 1..1 BackboneElement "A.2.4.1.3.2.1 - Popis vyšetření" """Popis vyšetření včetně kódu vyšetření, vyšetřované oblasti či vzorku, datum a čas odběru vzorku."""
      * formalizovany 1..1 BackboneElement "A.2.4.1.3.2.2 - Výsledek vyšetření formalizovaný" """Výsledek vyšetření textem a/nebo ve formě číselných a kódovaných výsledků měření. Obsah výsledku vyšetření se bude lišit podle typu vyšetření."""
      * provedl 0..* BackboneElement "A.2.4.1.3.2.3 - Provedl" """Identifikuje osobu, která  vyšetření provedla nebo je zdrojem informací o výsledku vyšetření. Tato osoba nemusí být totožná s autorem dokumentu."""
  * zakladniZivotniFunkce 0..* BackboneElement "A.2.4.1.4 - Základní životní funkce" """Výsledky měření základních životních funkcí pacienta: Požadované: Tepová frekvence, dechová frekvence, TK s uvedením strany měření, Volitelné: Saturace 02"""
    * typVysetreni 1..1 string "A.2.4.1.4.1 - Typ Vyšetření" """Klasifikace typu vyšetření. Zde fixní hodnota: vital-signs"""
    * text 1..1 BackboneElement "A.2.4.1.4.2 - Výsledek vyšetření textem" """Textový popis výsledku vyšetření"""
    * vysledek 1..1 BackboneElement "A.2.4.1.4.3 - Parametrický záznam vyšetření" """Parametrický zápis výsledku vyšetření."""
      * popisVysetreni 1..1 BackboneElement "A.2.4.1.4.3.1 - Popis vyšetření" """Popis vyšetření včetně kódu vyšetření, vyšetřované oblasti či vzorku, datum a čas odběru vzorku."""
      * formalizovany 1..1 BackboneElement "A.2.4.1.4.3.2 - Výsledek vyšetření formalizovaný" """Výsledek vyšetření textem a/nebo ve formě číselných a kódovaných výsledků měření. Obsah výsledku vyšetření se bude lišit podle typu vyšetření."""
      * provedl 0..* BackboneElement "A.2.4.1.4.3.3 - Provedl" """Identifikuje osobu, která  vyšetření provedla nebo je zdrojem informací o výsledku vyšetření. Tato osoba nemusí být totožná s autorem dokumentu."""
  * somatickeVysetreni 0..1 BackboneElement "A.2.4.1.5 - Somatické vyšetření" """Vyšetření pomocí smyslů vyšetřujícího (pohledem, poslechem, pohmatem a poklepem) a posuzování, zda se takto zjištěné nálezy odchylují od normy. Pokud ano, označujeme tyto odchylky jako objektivní příznaky (angl. signs). """
    * text 1..1 string "A.2.4.1.5.1 - Výsledek vyšetření textem" """Textový popis výsledku vyšetření. Mělo by být strukturováno podle časti těla (e.g. Hlava, krk, ramena, ruce, ...)"""
    * provedl 0..* BackboneElement "A.2.4.1.5.2 - Provedl" """Identifikuje osobu, která  vyšetření provedla nebo je zdrojem informací o výsledku vyšetření. Tato osoba nemusí být totožná s autorem dokumentu."""
* funkcniStav 0..1 BackboneElement "A.2.4.2 - Funkční stav" """Funkční stav lze hodnotit několika různými způsoby, obvykle se zaměřením na schopnosti osoby vykonávat základní aktivity každodenního života (ADL), které zahrnují základní sebeobsluhu, jako je koupání, krmení a toaleta a instrumentální aktivity každodenního života (IADL), které zahrnují činnosti jako vaření, nakupování a řízení vlastních záležitostí."""
  * datum 0..1 dateTime "A.2.4.2.1 - Datum a čas" """Datum a čas hodnocení funkčního stavu pacienta."""
  * provedl 0..* BackboneElement "A.2.4.2.2 - Provedl" """Identifikuje osobu, která  vyšetření provedla nebo je zdrojem informací o výsledku vyšetření. Tato osoba nemusí být totožná s autorem dokumentu."""
  * popis 1..1 string "A.2.4.2.3 - Popis" """Textový popis funkčního stavu pacienta."""
  * hodnoceniFormalizovane 0..* BackboneElement "A.2.4.2.4 - Hodnocení formalizované" """Formalizované hodnocení funkčního stavu pacienta dle jednotlivých hodnotících kategorií zvoleného systému hodnocení (např. MKF)"""
    * datumVzniku 0..1 dateTime "A.2.4.2.4.1 - Datum vzniku" """Datum vzniku funkčního omezení"""
    * text 0..1 BackboneElement "A.2.4.2.4.2 - Výsledek vyšetření textem" """Výsledek vyšetření volným textem."""
    * popis 1..1 BackboneElement "A.2.4.2.4.3 - Popis vyšetření" """Popis vyšetření včetně kódu. Jako výchozí systém pro hodnocení funkčního stavu byl zvolen mezinárodní klasifikační systém MKF. Další typy hodnotících škál mohou být doplněny v budoucích verzích standardu na základě potřeby a konsenzu odborné veřejnosti. """
    * formalizovany  1..1 BackboneElement "A.2.4.2.4.4 - Výsledek vyšetření formalizovaný" """Výsledek hodnocení funkčního stavu v dané kategorii hodnocení."""
