Logical: LogCzAlertsCz
Id: LogAlertsCz
Title: "A.2.2 - Urgentní informace (cz)"
Description: """Nemocniční propouštěcí zpráva - Urgentní informace - A.2.2"""

* alergie 1..* Base "A.2.2.1 - Alergie a intolerance" """Záznam alergie a intolerance je povinný. U pacientů, bez alergie či intolerance je nutné tento fakt explicitně vyjádřit příslušným kódem."""
* alergie.popis 0..1 string "A.2.2.1.1 - Popis alergie" """Textové doplnění informací volným textem. Je určeno pro zápis informací, které nelze zapsat strukturovaně."""
* alergie.puvodce 1..1 CodeableConcept "A.2.2.1.2 - Původce" """Látka, skupina látek nebo faktor prostředí, na které je pacient alergický nebo přecitlivělý. Původce je možné vyjádřit pomocí kódu substance, ATC skupiny nebo kódu produktu SÚKL (v případě léčivých přípravků)."""
* alergie.typReakce 0..1 CodeableConcept "A.2.2.1.3 - Typ reakce" """Typ (mechanismus) reakce: alergie, intolerance, nealergická hypersenzitivita."""
* alergie.reakce 0..* CodeableConcept "A.2.2.1.4 - Reakce" """Dosud známé projevy reakce na expozici pacienta původci, textem nebo kódem, včetně možnosti uvést způsob expozice a závažnost projevu."""
* alergie.riziko 0..1 CodeableConcept "A.2.2.1.5 - Riziko" """Stupeň závažnosti je definován jako „potenciální závažnost budoucích reakcí“. Stupeň závažnosti představuje klinické hodnocení nejhoršího scénáře budoucí reakce. Může být založeno na závažnosti minulých reakcí a na stupni ohrožení pacienta."""
* alergie.pocatekProjevu 0..1 BackboneElement "A.2.2.1.6 - Počátek období projevu" """Datum nebo období, ve kterém byla alergie nebo jiná nežádoucí reakce zaznamenána či klinicky stanovena. Může to být přesné datum a čas nebo hrubý údaj o datu (například pouze rok nebo měsíc a rok) nebo vyjádření pomocí kódu věkové fáze (dětství, adolescence apod.), resp. časového intervalu (2001 - 2005 apod.)."""
* alergie.pocatekProjevu.datum 0..1 dateTime "Počátek období projevu - datum" """Datum počátku nežádoucí reakce (např. první výskyt)."""
* alergie.pocatekProjevu.kod 0..1 CodeableConcept "Počátek období projevu - kód" """Vyjádření počátku reakce kódem např. věkové skupiny."""
* alergie.konecProjevu 0..1 BackboneElement "A.2.2.1.7 - Konec období projevu" """Datum nebo období, ve kterém byly projevy alergie nebo jiné nežádoucí reakce potlačeny nebo klinicky vyloučeny."""
* alergie.konecProjevu.datum 0..1 dateTime "Konec období projevu - datum"
* alergie.konecProjevu.kod 0..1 CodeableConcept "Konec období projevu - kód"
* alergie.stav 0..1 CodeableConcept "A.2.2.1.8 - Stav" """„Klinický stav“ vyjadřuje aktuální stav dispozice pacienta k nežádoucí reakci."""
* alergie.miraJIstoty 0..1 CodeableConcept "A.2.2.1.9 - Míra jistoty" """Umožňuje vyjádřit míru jistoty zapisujícího lékaře ve vztahu k údajům uvedeným v modelu alergie."""
* alergie.posledniProjev 0..1 dateTime "A.2.2.1.10 - Poslední projev" """Datum (a čas) poslední známé reakce (projevu)."""
* varovani 0..* BackboneElement "A.2.2.2 - Varování" """Varování relevantní pro danou hospitalizaci (např. vzácná onemocnění, komplikované stavy, přítomnost implantátu apod.)."""
* varovani.oznaceniVarovani 0..1 CodeableConcept "A.2.2.2.1 - Označení varování" """Název charakterizující typ či předmět varování"""
* varovani.kod 0..* CodeableConcept "A.2.2.2.3 - Onemocnění či stav" """Stav či onemocnění, které je zdrojem/příčinou pro varování."""
* varovani.specializovanyLekar 0..* BackboneElement "A.2.2.2.4 - Specializovaný lékař" """Kontaktní informace na specialistu, u kterého je pacient v péči - týká se především pacientů se vzácným onemocněním."""
* varovani.komentar 0..1 string "A.2.2.2.5 - Komentář" """Komentář/popis varování volným textem"""
* varovani.uroven 0..1 CodeableConcept "A.2.2.2.6 - Úroveň" """Úroveň závažnosti varování"""
* varovani.platnost 0..1 BackboneElement "A.2.2.2.7 - Období platnosti varování" """Umožňuje vyjádřit období ve kterém bylo varování aktivní. Týká se přechodných stavů."""
