Logical: LogCzDischargeDetailsCz
Id: LogDischargeDetailsCz
Title: "A.2.7 - Průběh hospitalizace"
Description: """Nemocniční propouštěcí zpráva - Průběh hospitalizace"""
/*
* diagnostickySouhrn 1..* Base "A.2.7.1 - Diagnostický souhrn" """Všechny problémy/diagnózy, které ovlivňují péči během hospitalizace nebo které je důležité zaznamenat pro zajištění kontinuity péče. V diagnostickém souhrnu se v souladu s mezinárodním doporučením rozlišuje mezi problémy léčenými během hospitalizace a ostatními (neléčenými) problémy. Léčené problémy jsou problémy, které byly během hospitalizace předmětem diagnostiky, terapie, ošetřování nebo (průběžného) sledování. Dále lze problémy rozdělit do tří kategorií: problémy přítomné při přijetí (POA), stavy získané během hospitalizace (HAC) a problémy, které nelze zařadit do žádné z těchto dvou kategorií (N/A). Diagnostický souhrn obsahuje všechny stavy tak, jak byly rozpoznány na konci hospitalizace, po všech vyšetřeních. Tento oddíl obsahuje stručný, dobře specifikovaný, kódovatelný souhrn problémů. Problémy jsou seřazeny podle důležitosti (hlavní problémy na prvním místě) během hospitalizace. Popis problému může být doplněn dalšími podrobnostmi v oddíle anamnézy a/nebo v oddíle Syntéza."""
* vyznamneVykony 1..* Base "A.2.7.2 - Významné výkony" """Operace a ostatní „instrumentální“ intervence (endoskopické, intravaskulární) provedené v průběhu hospitalizace a významné pro kontinuitu péče.Do této sekce nepatří čistě diagnostické výkony (MRI, CT a pod.). Pokud nebyl proveden žádný významný výkon, musí být tento fakt explicitně uveden pomocí kódu IPS Absent and Unknown Data."""
* zdrPomucky 1..* Base "A.2.7.3 - Zdravotní pomůcky a implantáty" """Zavedené implantáty a používané zdravotní pomůcky (zdravotnické prostředky), které ovlivňují nebo mohou ovlivňovat poskytování zdravotních služeb (diagnostiku i léčbu). Dále také zdravotnické prostředky odebrané v průběhu hospitalizace. Pokud je sekce prázdná, musí být explicitně uveden důvod pomocí kódového systému IPS Absent and Unknown Data"""
* vyznamnaLecba 0..* Base "A.2.7.4 - Další významná léčba" """Poskytnutá léčba, kterou nelze jednoznačně označit za významný výkon (ve smyslu předchozí definice), ale je významná – typicky chemoterapie, radioterapie, očišťovací metody (dialýza, hemoperfuze), metody podpory oběhu (kontrapulzace apod.), podání krevních derivátů případně další."""
* medikace 0..* Base "A.2.7.5 - Medikace" """Vybraná medikamentózní léčba v průběhu hospitalizace. Uvedou se ty léčivé přípravky, jejichž podávání bylo během hospitalizace ukončeno nebo pokračuje po propuštění pouze krátkodobě, přitom znalost jejich podání je významné pro další zdravotní péči (antibiotika kromě zcela rutinních, kortikosteroidy ve vysokých dávkách apod.) Léčivé přípravky, jejichž podávání bylo zahájeno během hospitalizace, ale je doporučeno i po propuštění, budou uvedeny v souhrnné tabulce v bloku Doporučení."""
* vysledky 0..* Base "A.2.7.6 - Výsledky vyšetření" """Výsledky významných funkčních, diagnostických a zobrazovacích vyšetření pro zajištění kontinuity péče, provedených v průběhu hospitalizace. Výsledky objednané, ale dosud nedodaných vyšetření (status = registered) by měly být prezentovány odděleně od výsledků již dodaných."""
* klinickeShrnuti 1..1 Base "A.2.7.7 - Klinické shrnutí" """Podrobný popis důvodu a průběhu hospitalizace (za celou hospitalizaci) strukturovaný dle jednotlivých problémů. Klinické shrnutí může být zakončeno klinickou úvahou (dif. diagnostika, vysvětlení souvislostí apod.) u klinicky složitých stavů."""
* klinickeShrnuti.problem 1..* Base "A.2.7.7.1 - Klinický souhrn problému" """Souhrnný popis důvodu a průběhu hospitalizace za konkrétní problém."""
* klinickeShrnuti.problem.text 1..* string "A.2.7.7.1.1 - Popis problému" """Popis problému textem."""
* klinickeShrnuti.problem.duvod 1..* Base "A.2.7.7.1.2- Důvod a průběh hospitalizace" """Podrobný popis důvodu a průběhu hospitalizace (za celou hospitalizaci)."""
* klinickeShrnuti.klinickaUvaha 0..1 Base "A.2.7.2- Klinická úvaha" """Klinické shrnutí může být zakončeno klinickou úvahou (dif. diagnostika, vysvětlení souvislostí apod.) u klinicky složitých stavů."""

* funkcniStav 0..1 Base "A.2.8.2 Funkční stav při propuštění" """Funkční stav lze hodnotit několika různými způsoby, obvykle se zaměřením na schopnosti osoby vykonávat základní aktivity každodenního života (ADL), které zahrnují základní sebeobsluhu, jako je koupání, krmení a toaleta a instrumentální aktivity každodenního života (IADL), které zahrnují činnosti jako vaření, nakupování a řízení vlastních záležitostí."""
  * datum 1..1 dateTime "A.2.8.2.1 Datum a čas" """Datum a čas hodnocení funkčního stavu pacienta."""
  * performer 0..* Base "A.2.8.2.2 Provedl" """Identifikuje osobu, která  vyšetření provedla nebo je zdrojem informací o výsledku vyšetření. Tato osoba nemusí být totožná s autorem dokumentu."""
  * popis 0..1 string "A.2.8.2.3 Popis" """Textový popis funkčního stavu pacienta."""
  * formalizovaneHodnoceni 0..* Base "A.2.8.2.4 Hodnocení formalizované" """Formalizované hodnocení funkčního stavu pacienta dle jednotlivých hodnotících kategorií (např. MKF)."""
    * datumVzniku 0..1 date "A.2.8.2.4.1 Datum vzniku" """Datum vzniku funkčního omezení."""
    * vysledekTextem 0..1 string "A.2.8.2.4.2 Výsledek vyšetření textem" """Výsledek vyšetření volným textem."""
    * popisVysetreni 1..1 CodeableConcept "A.2.8.2.4.3 Popis vyšetření" """Popis vyšetření včetně kódu. Jako výchozí systém pro hodnocení funkčního stavu byl zvolen mezinárodní klasifikační systém MKF. Další typy hodnotících škál mohou být doplněny v budoucích verzích standardu na základě potřeby a konsenzu odborné veřejnosti."""
    * vysledek 1..1 CodeableConcept "A.2.8.2.4.4 Výsledek vyšetření formalizovaný" """Výsledek hodnocení funkčního stavu v dané kategorii hodnocení."""
*/